# Neural SDE — Data Science minor @ HSE | 2026
# Authors: @trmif | @moriavohus | @rrqwt

title: "Neural SDE — курсовой проект"
author: ""
copyright: ""

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - dollarmath
    - colon_fence

html:
  use_issues_button: false
  use_repository_button: false
  extra_footer: ""
