# Beyond Infinity: Neural SDEs in Practice
# Data Science minor @ HSE | 2026
# Authors: @trmif | @moriavohus | @rrqwt

title: "Beyond Infinity: Neural SDEs in Practice"
author: ""
copyright: ""

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - dollarmath
    - colon_fence

html:
  use_issues_button: false
  use_repository_button: false
  extra_footer: ""
